import type { Metadata } from "next";
import { Open_Sans, Merriweather } from "next/font/google";
import "./globals.css";
import { Navbar } from "./NavBar";

const openSans = Open_Sans({ subsets: ["latin"], display: "swap" });

const Merri_Weather = Merriweather({
  subsets: ["latin"],
  display: "swap",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={Merri_Weather.className} lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
